Updated basics/nested-routing to v4.
actix/examples pull request #483
Opened 2022-01-29 12:16 UTC by cgubbin

Changed header attachment in test to use `insert_header`.

2022-01-29 17:44 UTC, robjtede requested changes

2022-01-30 20:06 UTC, cgubbin commented on basics/nested-routing/Cargo.toml
> +actix-rt = "2.6.0"
I fixed this. Thank you.

2022-01-30 20:06 UTC, cgubbin commented on basics/nested-routing/Cargo.toml
> +actix-service = "2.0.2"
I removed actix-service and imported the from actix-web::dev.

2022-01-30 20:09 UTC, cgubbin commented on basics/nested-routing/Cargo.toml
> +bytes = "1.1.0"
The `bytes` crate was actually an unused dependancy. I removed it. I am sorry this one was so messy, it was my first ever pull request! I have a much better idea what I'm doing now.

2022-01-30 21:51 UTC, robjtede approved these changes
Nice one. Thanks.

2022-01-30 21:51 UTC, merged